// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// EventSender is an autogenerated mock type for the EventSender type
type EventSender struct {
	mock.Mock
}

type EventSender_Expecter struct {
	mock *mock.Mock
}

func (_m *EventSender) EXPECT() *EventSender_Expecter {
	return &EventSender_Expecter{mock: &_m.Mock}
}

// SendPartnershipCreated provides a mock function with given fields: ctx, partnershipID, user1ID, user2ID
func (_m *EventSender) SendPartnershipCreated(ctx context.Context, partnershipID string, user1ID string, user2ID string) error {
	ret := _m.Called(ctx, partnershipID, user1ID, user2ID)

	if len(ret) == 0 {
		panic("no return value specified for SendPartnershipCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, partnershipID, user1ID, user2ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventSender_SendPartnershipCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPartnershipCreated'
type EventSender_SendPartnershipCreated_Call struct {
	*mock.Call
}

// SendPartnershipCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - partnershipID string
//   - user1ID string
//   - user2ID string
func (_e *EventSender_Expecter) SendPartnershipCreated(ctx interface{}, partnershipID interface{}, user1ID interface{}, user2ID interface{}) *EventSender_SendPartnershipCreated_Call {
	return &EventSender_SendPartnershipCreated_Call{Call: _e.mock.On("SendPartnershipCreated", ctx, partnershipID, user1ID, user2ID)}
}

func (_c *EventSender_SendPartnershipCreated_Call) Run(run func(ctx context.Context, partnershipID string, user1ID string, user2ID string)) *EventSender_SendPartnershipCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *EventSender_SendPartnershipCreated_Call) Return(_a0 error) *EventSender_SendPartnershipCreated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventSender_SendPartnershipCreated_Call) RunAndReturn(run func(context.Context, string, string, string) error) *EventSender_SendPartnershipCreated_Call {
	_c.Call.Return(run)
	return _c
}

// SendPartnershipTerminated provides a mock function with given fields: ctx, partnershipID
func (_m *EventSender) SendPartnershipTerminated(ctx context.Context, partnershipID string) error {
	ret := _m.Called(ctx, partnershipID)

	if len(ret) == 0 {
		panic("no return value specified for SendPartnershipTerminated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, partnershipID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventSender_SendPartnershipTerminated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPartnershipTerminated'
type EventSender_SendPartnershipTerminated_Call struct {
	*mock.Call
}

// SendPartnershipTerminated is a helper method to define mock.On call
//   - ctx context.Context
//   - partnershipID string
func (_e *EventSender_Expecter) SendPartnershipTerminated(ctx interface{}, partnershipID interface{}) *EventSender_SendPartnershipTerminated_Call {
	return &EventSender_SendPartnershipTerminated_Call{Call: _e.mock.On("SendPartnershipTerminated", ctx, partnershipID)}
}

func (_c *EventSender_SendPartnershipTerminated_Call) Run(run func(ctx context.Context, partnershipID string)) *EventSender_SendPartnershipTerminated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *EventSender_SendPartnershipTerminated_Call) Return(_a0 error) *EventSender_SendPartnershipTerminated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventSender_SendPartnershipTerminated_Call) RunAndReturn(run func(context.Context, string) error) *EventSender_SendPartnershipTerminated_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventSender creates a new instance of EventSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventSender {
	mock := &EventSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
