// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: models/auth_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserModel) Reset() {
	*x = UserModel{}
	mi := &file_models_auth_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserModel) ProtoMessage() {}

func (x *UserModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_auth_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserModel.ProtoReflect.Descriptor instead.
func (*UserModel) Descriptor() ([]byte, []int) {
	return file_models_auth_model_proto_rawDescGZIP(), []int{0}
}

func (x *UserModel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserModel) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserModel) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserModel) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type UserUpsertModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpsertModel) Reset() {
	*x = UserUpsertModel{}
	mi := &file_models_auth_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpsertModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpsertModel) ProtoMessage() {}

func (x *UserUpsertModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_auth_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpsertModel.ProtoReflect.Descriptor instead.
func (*UserUpsertModel) Descriptor() ([]byte, []int) {
	return file_models_auth_model_proto_rawDescGZIP(), []int{1}
}

func (x *UserUpsertModel) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserUpsertModel) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserUpsertModel) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PartnershipModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Player1Id     uint64                 `protobuf:"varint,2,opt,name=player1_id,json=player1Id,proto3" json:"player1_id,omitempty"`
	Player2Id     uint64                 `protobuf:"varint,3,opt,name=player2_id,json=player2Id,proto3" json:"player2_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartnershipModel) Reset() {
	*x = PartnershipModel{}
	mi := &file_models_auth_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartnershipModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnershipModel) ProtoMessage() {}

func (x *PartnershipModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_auth_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnershipModel.ProtoReflect.Descriptor instead.
func (*PartnershipModel) Descriptor() ([]byte, []int) {
	return file_models_auth_model_proto_rawDescGZIP(), []int{2}
}

func (x *PartnershipModel) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PartnershipModel) GetPlayer1Id() uint64 {
	if x != nil {
		return x.Player1Id
	}
	return 0
}

func (x *PartnershipModel) GetPlayer2Id() uint64 {
	if x != nil {
		return x.Player2Id
	}
	return 0
}

func (x *PartnershipModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type PartnershipUpsertModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player1Id     uint64                 `protobuf:"varint,1,opt,name=player1_id,json=player1Id,proto3" json:"player1_id,omitempty"`
	Player2Id     uint64                 `protobuf:"varint,2,opt,name=player2_id,json=player2Id,proto3" json:"player2_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartnershipUpsertModel) Reset() {
	*x = PartnershipUpsertModel{}
	mi := &file_models_auth_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartnershipUpsertModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartnershipUpsertModel) ProtoMessage() {}

func (x *PartnershipUpsertModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_auth_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartnershipUpsertModel.ProtoReflect.Descriptor instead.
func (*PartnershipUpsertModel) Descriptor() ([]byte, []int) {
	return file_models_auth_model_proto_rawDescGZIP(), []int{3}
}

func (x *PartnershipUpsertModel) GetPlayer1Id() uint64 {
	if x != nil {
		return x.Player1Id
	}
	return 0
}

func (x *PartnershipUpsertModel) GetPlayer2Id() uint64 {
	if x != nil {
		return x.Player2Id
	}
	return 0
}

var File_models_auth_model_proto protoreflect.FileDescriptor

const file_models_auth_model_proto_rawDesc = "" +
	"\n" +
	"\x17models/auth_model.proto\x12\x0eauth.models.v1\"r\n" +
	"\tUserModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x04 \x01(\tR\fpasswordHash\"_\n" +
	"\x0fUserUpsertModel\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"x\n" +
	"\x10PartnershipModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"player1_id\x18\x02 \x01(\x04R\tplayer1Id\x12\x1d\n" +
	"\n" +
	"player2_id\x18\x03 \x01(\x04R\tplayer2Id\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"V\n" +
	"\x16PartnershipUpsertModel\x12\x1d\n" +
	"\n" +
	"player1_id\x18\x01 \x01(\x04R\tplayer1Id\x12\x1d\n" +
	"\n" +
	"player2_id\x18\x02 \x01(\x04R\tplayer2IdBCZAgithub.com/nineteen-night/empty-room-game/internal/auth/pb/modelsb\x06proto3"

var (
	file_models_auth_model_proto_rawDescOnce sync.Once
	file_models_auth_model_proto_rawDescData []byte
)

func file_models_auth_model_proto_rawDescGZIP() []byte {
	file_models_auth_model_proto_rawDescOnce.Do(func() {
		file_models_auth_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_auth_model_proto_rawDesc), len(file_models_auth_model_proto_rawDesc)))
	})
	return file_models_auth_model_proto_rawDescData
}

var file_models_auth_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_models_auth_model_proto_goTypes = []any{
	(*UserModel)(nil),              // 0: auth.models.v1.UserModel
	(*UserUpsertModel)(nil),        // 1: auth.models.v1.UserUpsertModel
	(*PartnershipModel)(nil),       // 2: auth.models.v1.PartnershipModel
	(*PartnershipUpsertModel)(nil), // 3: auth.models.v1.PartnershipUpsertModel
}
var file_models_auth_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_auth_model_proto_init() }
func file_models_auth_model_proto_init() {
	if File_models_auth_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_auth_model_proto_rawDesc), len(file_models_auth_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_auth_model_proto_goTypes,
		DependencyIndexes: file_models_auth_model_proto_depIdxs,
		MessageInfos:      file_models_auth_model_proto_msgTypes,
	}.Build()
	File_models_auth_model_proto = out.File
	file_models_auth_model_proto_goTypes = nil
	file_models_auth_model_proto_depIdxs = nil
}
