// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: models/game_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Комната
type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomNumber    int32                  `protobuf:"varint,1,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_models_game_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_models_game_model_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetRoomNumber() int32 {
	if x != nil {
		return x.RoomNumber
	}
	return 0
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Игровая сессия
type GameSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartnershipId string                 `protobuf:"bytes,1,opt,name=partnership_id,json=partnershipId,proto3" json:"partnership_id,omitempty"`
	User1Id       string                 `protobuf:"bytes,2,opt,name=user1_id,json=user1Id,proto3" json:"user1_id,omitempty"`
	User2Id       string                 `protobuf:"bytes,3,opt,name=user2_id,json=user2Id,proto3" json:"user2_id,omitempty"`
	CurrentRoom   int32                  `protobuf:"varint,4,opt,name=current_room,json=currentRoom,proto3" json:"current_room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSession) Reset() {
	*x = GameSession{}
	mi := &file_models_game_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSession) ProtoMessage() {}

func (x *GameSession) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSession.ProtoReflect.Descriptor instead.
func (*GameSession) Descriptor() ([]byte, []int) {
	return file_models_game_model_proto_rawDescGZIP(), []int{1}
}

func (x *GameSession) GetPartnershipId() string {
	if x != nil {
		return x.PartnershipId
	}
	return ""
}

func (x *GameSession) GetUser1Id() string {
	if x != nil {
		return x.User1Id
	}
	return ""
}

func (x *GameSession) GetUser2Id() string {
	if x != nil {
		return x.User2Id
	}
	return ""
}

func (x *GameSession) GetCurrentRoom() int32 {
	if x != nil {
		return x.CurrentRoom
	}
	return 0
}

// Состояние игры
type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentRoom   int32                  `protobuf:"varint,1,opt,name=current_room,json=currentRoom,proto3" json:"current_room,omitempty"`
	RoomInfo      *Room                  `protobuf:"bytes,2,opt,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_models_game_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_models_game_model_proto_rawDescGZIP(), []int{2}
}

func (x *GameState) GetCurrentRoom() int32 {
	if x != nil {
		return x.CurrentRoom
	}
	return 0
}

func (x *GameState) GetRoomInfo() *Room {
	if x != nil {
		return x.RoomInfo
	}
	return nil
}

var File_models_game_model_proto protoreflect.FileDescriptor

const file_models_game_model_proto_rawDesc = "" +
	"\n" +
	"\x17models/game_model.proto\x12\x0egame.models.v1\"]\n" +
	"\x04Room\x12\x1f\n" +
	"\vroom_number\x18\x01 \x01(\x05R\n" +
	"roomNumber\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x8d\x01\n" +
	"\vGameSession\x12%\n" +
	"\x0epartnership_id\x18\x01 \x01(\tR\rpartnershipId\x12\x19\n" +
	"\buser1_id\x18\x02 \x01(\tR\auser1Id\x12\x19\n" +
	"\buser2_id\x18\x03 \x01(\tR\auser2Id\x12!\n" +
	"\fcurrent_room\x18\x04 \x01(\x05R\vcurrentRoom\"a\n" +
	"\tGameState\x12!\n" +
	"\fcurrent_room\x18\x01 \x01(\x05R\vcurrentRoom\x121\n" +
	"\troom_info\x18\x02 \x01(\v2\x14.game.models.v1.RoomR\broomInfoBCZAgithub.com/nineteen-night/empty-room-game/internal/game/pb/modelsb\x06proto3"

var (
	file_models_game_model_proto_rawDescOnce sync.Once
	file_models_game_model_proto_rawDescData []byte
)

func file_models_game_model_proto_rawDescGZIP() []byte {
	file_models_game_model_proto_rawDescOnce.Do(func() {
		file_models_game_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_game_model_proto_rawDesc), len(file_models_game_model_proto_rawDesc)))
	})
	return file_models_game_model_proto_rawDescData
}

var file_models_game_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_models_game_model_proto_goTypes = []any{
	(*Room)(nil),        // 0: game.models.v1.Room
	(*GameSession)(nil), // 1: game.models.v1.GameSession
	(*GameState)(nil),   // 2: game.models.v1.GameState
}
var file_models_game_model_proto_depIdxs = []int32{
	0, // 0: game.models.v1.GameState.room_info:type_name -> game.models.v1.Room
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_game_model_proto_init() }
func file_models_game_model_proto_init() {
	if File_models_game_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_game_model_proto_rawDesc), len(file_models_game_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_game_model_proto_goTypes,
		DependencyIndexes: file_models_game_model_proto_depIdxs,
		MessageInfos:      file_models_game_model_proto_msgTypes,
	}.Build()
	File_models_game_model_proto = out.File
	file_models_game_model_proto_goTypes = nil
	file_models_game_model_proto_depIdxs = nil
}
