// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: game_api/game.proto

package game_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameService_GetGameSessionsByIDs_FullMethodName = "/game.service.v1.GameService/GetGameSessionsByIDs"
	GameService_UpsertGameSessions_FullMethodName   = "/game.service.v1.GameService/UpsertGameSessions"
	GameService_GetGameStatesByIDs_FullMethodName   = "/game.service.v1.GameService/GetGameStatesByIDs"
	GameService_UpsertGameStates_FullMethodName     = "/game.service.v1.GameService/UpsertGameStates"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	// Игровые сессии
	GetGameSessionsByIDs(ctx context.Context, in *GetGameSessionsByIDsRequest, opts ...grpc.CallOption) (*GetGameSessionsByIDsResponse, error)
	UpsertGameSessions(ctx context.Context, in *UpsertGameSessionsRequest, opts ...grpc.CallOption) (*UpsertGameSessionsResponse, error)
	// Состояния игр
	GetGameStatesByIDs(ctx context.Context, in *GetGameStatesByIDsRequest, opts ...grpc.CallOption) (*GetGameStatesByIDsResponse, error)
	UpsertGameStates(ctx context.Context, in *UpsertGameStatesRequest, opts ...grpc.CallOption) (*UpsertGameStatesResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) GetGameSessionsByIDs(ctx context.Context, in *GetGameSessionsByIDsRequest, opts ...grpc.CallOption) (*GetGameSessionsByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameSessionsByIDsResponse)
	err := c.cc.Invoke(ctx, GameService_GetGameSessionsByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpsertGameSessions(ctx context.Context, in *UpsertGameSessionsRequest, opts ...grpc.CallOption) (*UpsertGameSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertGameSessionsResponse)
	err := c.cc.Invoke(ctx, GameService_UpsertGameSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGameStatesByIDs(ctx context.Context, in *GetGameStatesByIDsRequest, opts ...grpc.CallOption) (*GetGameStatesByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameStatesByIDsResponse)
	err := c.cc.Invoke(ctx, GameService_GetGameStatesByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) UpsertGameStates(ctx context.Context, in *UpsertGameStatesRequest, opts ...grpc.CallOption) (*UpsertGameStatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertGameStatesResponse)
	err := c.cc.Invoke(ctx, GameService_UpsertGameStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility.
type GameServiceServer interface {
	// Игровые сессии
	GetGameSessionsByIDs(context.Context, *GetGameSessionsByIDsRequest) (*GetGameSessionsByIDsResponse, error)
	UpsertGameSessions(context.Context, *UpsertGameSessionsRequest) (*UpsertGameSessionsResponse, error)
	// Состояния игр
	GetGameStatesByIDs(context.Context, *GetGameStatesByIDsRequest) (*GetGameStatesByIDsResponse, error)
	UpsertGameStates(context.Context, *UpsertGameStatesRequest) (*UpsertGameStatesResponse, error)
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServiceServer struct{}

func (UnimplementedGameServiceServer) GetGameSessionsByIDs(context.Context, *GetGameSessionsByIDsRequest) (*GetGameSessionsByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameSessionsByIDs not implemented")
}
func (UnimplementedGameServiceServer) UpsertGameSessions(context.Context, *UpsertGameSessionsRequest) (*UpsertGameSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertGameSessions not implemented")
}
func (UnimplementedGameServiceServer) GetGameStatesByIDs(context.Context, *GetGameStatesByIDsRequest) (*GetGameStatesByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameStatesByIDs not implemented")
}
func (UnimplementedGameServiceServer) UpsertGameStates(context.Context, *UpsertGameStatesRequest) (*UpsertGameStatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertGameStates not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}
func (UnimplementedGameServiceServer) testEmbeddedByValue()                     {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	// If the following call panics, it indicates UnimplementedGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_GetGameSessionsByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameSessionsByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGameSessionsByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGameSessionsByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGameSessionsByIDs(ctx, req.(*GetGameSessionsByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpsertGameSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertGameSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpsertGameSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_UpsertGameSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpsertGameSessions(ctx, req.(*UpsertGameSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGameStatesByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameStatesByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGameStatesByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGameStatesByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGameStatesByIDs(ctx, req.(*GetGameStatesByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_UpsertGameStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertGameStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).UpsertGameStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_UpsertGameStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).UpsertGameStates(ctx, req.(*UpsertGameStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.service.v1.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGameSessionsByIDs",
			Handler:    _GameService_GetGameSessionsByIDs_Handler,
		},
		{
			MethodName: "UpsertGameSessions",
			Handler:    _GameService_UpsertGameSessions_Handler,
		},
		{
			MethodName: "GetGameStatesByIDs",
			Handler:    _GameService_GetGameStatesByIDs_Handler,
		},
		{
			MethodName: "UpsertGameStates",
			Handler:    _GameService_UpsertGameStates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game_api/game.proto",
}
