// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: game_api/game.proto

package game_api

import (
	models "github.com/nineteen-night/empty-room-game/internal/game/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запросы для игровых сессий
type GetGameSessionsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameSessionsByIDsRequest) Reset() {
	*x = GetGameSessionsByIDsRequest{}
	mi := &file_game_api_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameSessionsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameSessionsByIDsRequest) ProtoMessage() {}

func (x *GetGameSessionsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_api_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameSessionsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetGameSessionsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_game_api_game_proto_rawDescGZIP(), []int{0}
}

func (x *GetGameSessionsByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetGameSessionsByIDsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	GameSessions  []*models.GameSessionModel `protobuf:"bytes,1,rep,name=game_sessions,json=gameSessions,proto3" json:"game_sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameSessionsByIDsResponse) Reset() {
	*x = GetGameSessionsByIDsResponse{}
	mi := &file_game_api_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameSessionsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameSessionsByIDsResponse) ProtoMessage() {}

func (x *GetGameSessionsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_api_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameSessionsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetGameSessionsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_game_api_game_proto_rawDescGZIP(), []int{1}
}

func (x *GetGameSessionsByIDsResponse) GetGameSessions() []*models.GameSessionModel {
	if x != nil {
		return x.GameSessions
	}
	return nil
}

type UpsertGameSessionsRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	GameSessions  []*models.GameSessionUpsertModel `protobuf:"bytes,1,rep,name=game_sessions,json=gameSessions,proto3" json:"game_sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertGameSessionsRequest) Reset() {
	*x = UpsertGameSessionsRequest{}
	mi := &file_game_api_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertGameSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertGameSessionsRequest) ProtoMessage() {}

func (x *UpsertGameSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_api_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertGameSessionsRequest.ProtoReflect.Descriptor instead.
func (*UpsertGameSessionsRequest) Descriptor() ([]byte, []int) {
	return file_game_api_game_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertGameSessionsRequest) GetGameSessions() []*models.GameSessionUpsertModel {
	if x != nil {
		return x.GameSessions
	}
	return nil
}

type UpsertGameSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertGameSessionsResponse) Reset() {
	*x = UpsertGameSessionsResponse{}
	mi := &file_game_api_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertGameSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertGameSessionsResponse) ProtoMessage() {}

func (x *UpsertGameSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_api_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertGameSessionsResponse.ProtoReflect.Descriptor instead.
func (*UpsertGameSessionsResponse) Descriptor() ([]byte, []int) {
	return file_game_api_game_proto_rawDescGZIP(), []int{3}
}

// Запросы для состояний игр
type GetGameStatesByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStatesByIDsRequest) Reset() {
	*x = GetGameStatesByIDsRequest{}
	mi := &file_game_api_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStatesByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStatesByIDsRequest) ProtoMessage() {}

func (x *GetGameStatesByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_api_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStatesByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetGameStatesByIDsRequest) Descriptor() ([]byte, []int) {
	return file_game_api_game_proto_rawDescGZIP(), []int{4}
}

func (x *GetGameStatesByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetGameStatesByIDsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	GameStates    []*models.GameStateModel `protobuf:"bytes,1,rep,name=game_states,json=gameStates,proto3" json:"game_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStatesByIDsResponse) Reset() {
	*x = GetGameStatesByIDsResponse{}
	mi := &file_game_api_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStatesByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStatesByIDsResponse) ProtoMessage() {}

func (x *GetGameStatesByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_api_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStatesByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetGameStatesByIDsResponse) Descriptor() ([]byte, []int) {
	return file_game_api_game_proto_rawDescGZIP(), []int{5}
}

func (x *GetGameStatesByIDsResponse) GetGameStates() []*models.GameStateModel {
	if x != nil {
		return x.GameStates
	}
	return nil
}

type UpsertGameStatesRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	GameStates    []*models.GameStateUpsertModel `protobuf:"bytes,1,rep,name=game_states,json=gameStates,proto3" json:"game_states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertGameStatesRequest) Reset() {
	*x = UpsertGameStatesRequest{}
	mi := &file_game_api_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertGameStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertGameStatesRequest) ProtoMessage() {}

func (x *UpsertGameStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_api_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertGameStatesRequest.ProtoReflect.Descriptor instead.
func (*UpsertGameStatesRequest) Descriptor() ([]byte, []int) {
	return file_game_api_game_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertGameStatesRequest) GetGameStates() []*models.GameStateUpsertModel {
	if x != nil {
		return x.GameStates
	}
	return nil
}

type UpsertGameStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertGameStatesResponse) Reset() {
	*x = UpsertGameStatesResponse{}
	mi := &file_game_api_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertGameStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertGameStatesResponse) ProtoMessage() {}

func (x *UpsertGameStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_api_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertGameStatesResponse.ProtoReflect.Descriptor instead.
func (*UpsertGameStatesResponse) Descriptor() ([]byte, []int) {
	return file_game_api_game_proto_rawDescGZIP(), []int{7}
}

var File_game_api_game_proto protoreflect.FileDescriptor

const file_game_api_game_proto_rawDesc = "" +
	"\n" +
	"\x13game_api/game.proto\x12\x0fgame.service.v1\x1a\x17models/game_model.proto\x1a\x1cgoogle/api/annotations.proto\"/\n" +
	"\x1bGetGameSessionsByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"e\n" +
	"\x1cGetGameSessionsByIDsResponse\x12E\n" +
	"\rgame_sessions\x18\x01 \x03(\v2 .game.models.v1.GameSessionModelR\fgameSessions\"h\n" +
	"\x19UpsertGameSessionsRequest\x12K\n" +
	"\rgame_sessions\x18\x01 \x03(\v2&.game.models.v1.GameSessionUpsertModelR\fgameSessions\"\x1c\n" +
	"\x1aUpsertGameSessionsResponse\"-\n" +
	"\x19GetGameStatesByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"]\n" +
	"\x1aGetGameStatesByIDsResponse\x12?\n" +
	"\vgame_states\x18\x01 \x03(\v2\x1e.game.models.v1.GameStateModelR\n" +
	"gameStates\"`\n" +
	"\x17UpsertGameStatesRequest\x12E\n" +
	"\vgame_states\x18\x01 \x03(\v2$.game.models.v1.GameStateUpsertModelR\n" +
	"gameStates\"\x1a\n" +
	"\x18UpsertGameStatesResponse2\xd9\x04\n" +
	"\vGameService\x12\x99\x01\n" +
	"\x14GetGameSessionsByIDs\x12,.game.service.v1.GetGameSessionsByIDsRequest\x1a-.game.service.v1.GetGameSessionsByIDsResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/game-sessions/get-by-ids\x12\x8f\x01\n" +
	"\x12UpsertGameSessions\x12*.game.service.v1.UpsertGameSessionsRequest\x1a+.game.service.v1.UpsertGameSessionsResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/game-sessions/upsert\x12\x91\x01\n" +
	"\x12GetGameStatesByIDs\x12*.game.service.v1.GetGameStatesByIDsRequest\x1a+.game.service.v1.GetGameStatesByIDsResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/game-states/get-by-ids\x12\x87\x01\n" +
	"\x10UpsertGameStates\x12(.game.service.v1.UpsertGameStatesRequest\x1a).game.service.v1.UpsertGameStatesResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/game-states/upsertBEZCgithub.com/nineteen-night/empty-room-game/internal/game/pb/game_apib\x06proto3"

var (
	file_game_api_game_proto_rawDescOnce sync.Once
	file_game_api_game_proto_rawDescData []byte
)

func file_game_api_game_proto_rawDescGZIP() []byte {
	file_game_api_game_proto_rawDescOnce.Do(func() {
		file_game_api_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_api_game_proto_rawDesc), len(file_game_api_game_proto_rawDesc)))
	})
	return file_game_api_game_proto_rawDescData
}

var file_game_api_game_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_game_api_game_proto_goTypes = []any{
	(*GetGameSessionsByIDsRequest)(nil),   // 0: game.service.v1.GetGameSessionsByIDsRequest
	(*GetGameSessionsByIDsResponse)(nil),  // 1: game.service.v1.GetGameSessionsByIDsResponse
	(*UpsertGameSessionsRequest)(nil),     // 2: game.service.v1.UpsertGameSessionsRequest
	(*UpsertGameSessionsResponse)(nil),    // 3: game.service.v1.UpsertGameSessionsResponse
	(*GetGameStatesByIDsRequest)(nil),     // 4: game.service.v1.GetGameStatesByIDsRequest
	(*GetGameStatesByIDsResponse)(nil),    // 5: game.service.v1.GetGameStatesByIDsResponse
	(*UpsertGameStatesRequest)(nil),       // 6: game.service.v1.UpsertGameStatesRequest
	(*UpsertGameStatesResponse)(nil),      // 7: game.service.v1.UpsertGameStatesResponse
	(*models.GameSessionModel)(nil),       // 8: game.models.v1.GameSessionModel
	(*models.GameSessionUpsertModel)(nil), // 9: game.models.v1.GameSessionUpsertModel
	(*models.GameStateModel)(nil),         // 10: game.models.v1.GameStateModel
	(*models.GameStateUpsertModel)(nil),   // 11: game.models.v1.GameStateUpsertModel
}
var file_game_api_game_proto_depIdxs = []int32{
	8,  // 0: game.service.v1.GetGameSessionsByIDsResponse.game_sessions:type_name -> game.models.v1.GameSessionModel
	9,  // 1: game.service.v1.UpsertGameSessionsRequest.game_sessions:type_name -> game.models.v1.GameSessionUpsertModel
	10, // 2: game.service.v1.GetGameStatesByIDsResponse.game_states:type_name -> game.models.v1.GameStateModel
	11, // 3: game.service.v1.UpsertGameStatesRequest.game_states:type_name -> game.models.v1.GameStateUpsertModel
	0,  // 4: game.service.v1.GameService.GetGameSessionsByIDs:input_type -> game.service.v1.GetGameSessionsByIDsRequest
	2,  // 5: game.service.v1.GameService.UpsertGameSessions:input_type -> game.service.v1.UpsertGameSessionsRequest
	4,  // 6: game.service.v1.GameService.GetGameStatesByIDs:input_type -> game.service.v1.GetGameStatesByIDsRequest
	6,  // 7: game.service.v1.GameService.UpsertGameStates:input_type -> game.service.v1.UpsertGameStatesRequest
	1,  // 8: game.service.v1.GameService.GetGameSessionsByIDs:output_type -> game.service.v1.GetGameSessionsByIDsResponse
	3,  // 9: game.service.v1.GameService.UpsertGameSessions:output_type -> game.service.v1.UpsertGameSessionsResponse
	5,  // 10: game.service.v1.GameService.GetGameStatesByIDs:output_type -> game.service.v1.GetGameStatesByIDsResponse
	7,  // 11: game.service.v1.GameService.UpsertGameStates:output_type -> game.service.v1.UpsertGameStatesResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_game_api_game_proto_init() }
func file_game_api_game_proto_init() {
	if File_game_api_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_api_game_proto_rawDesc), len(file_game_api_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_api_game_proto_goTypes,
		DependencyIndexes: file_game_api_game_proto_depIdxs,
		MessageInfos:      file_game_api_game_proto_msgTypes,
	}.Build()
	File_game_api_game_proto = out.File
	file_game_api_game_proto_goTypes = nil
	file_game_api_game_proto_depIdxs = nil
}
