// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: game_api/game.proto

package game_api

import (
	models "github.com/nineteen-night/empty-room-game/internal/game/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запросы
type GetGameStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartnershipId string                 `protobuf:"bytes,1,opt,name=partnership_id,json=partnershipId,proto3" json:"partnership_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateRequest) Reset() {
	*x = GetGameStateRequest{}
	mi := &file_game_api_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateRequest) ProtoMessage() {}

func (x *GetGameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_api_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateRequest.ProtoReflect.Descriptor instead.
func (*GetGameStateRequest) Descriptor() ([]byte, []int) {
	return file_game_api_game_proto_rawDescGZIP(), []int{0}
}

func (x *GetGameStateRequest) GetPartnershipId() string {
	if x != nil {
		return x.PartnershipId
	}
	return ""
}

type GetGameStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameState     *models.GameState      `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStateResponse) Reset() {
	*x = GetGameStateResponse{}
	mi := &file_game_api_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStateResponse) ProtoMessage() {}

func (x *GetGameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_api_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStateResponse.ProtoReflect.Descriptor instead.
func (*GetGameStateResponse) Descriptor() ([]byte, []int) {
	return file_game_api_game_proto_rawDescGZIP(), []int{1}
}

func (x *GetGameStateResponse) GetGameState() *models.GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

type MoveToNextRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartnershipId string                 `protobuf:"bytes,1,opt,name=partnership_id,json=partnershipId,proto3" json:"partnership_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToNextRoomRequest) Reset() {
	*x = MoveToNextRoomRequest{}
	mi := &file_game_api_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToNextRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToNextRoomRequest) ProtoMessage() {}

func (x *MoveToNextRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_api_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToNextRoomRequest.ProtoReflect.Descriptor instead.
func (*MoveToNextRoomRequest) Descriptor() ([]byte, []int) {
	return file_game_api_game_proto_rawDescGZIP(), []int{2}
}

func (x *MoveToNextRoomRequest) GetPartnershipId() string {
	if x != nil {
		return x.PartnershipId
	}
	return ""
}

type MoveToNextRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewGameState  *models.GameState      `protobuf:"bytes,1,opt,name=new_game_state,json=newGameState,proto3" json:"new_game_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveToNextRoomResponse) Reset() {
	*x = MoveToNextRoomResponse{}
	mi := &file_game_api_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveToNextRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveToNextRoomResponse) ProtoMessage() {}

func (x *MoveToNextRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_api_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveToNextRoomResponse.ProtoReflect.Descriptor instead.
func (*MoveToNextRoomResponse) Descriptor() ([]byte, []int) {
	return file_game_api_game_proto_rawDescGZIP(), []int{3}
}

func (x *MoveToNextRoomResponse) GetNewGameState() *models.GameState {
	if x != nil {
		return x.NewGameState
	}
	return nil
}

var File_game_api_game_proto protoreflect.FileDescriptor

const file_game_api_game_proto_rawDesc = "" +
	"\n" +
	"\x13game_api/game.proto\x12\x0fgame.service.v1\x1a\x17models/game_model.proto\x1a\x1cgoogle/api/annotations.proto\"<\n" +
	"\x13GetGameStateRequest\x12%\n" +
	"\x0epartnership_id\x18\x01 \x01(\tR\rpartnershipId\"P\n" +
	"\x14GetGameStateResponse\x128\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x19.game.models.v1.GameStateR\tgameState\">\n" +
	"\x15MoveToNextRoomRequest\x12%\n" +
	"\x0epartnership_id\x18\x01 \x01(\tR\rpartnershipId\"Y\n" +
	"\x16MoveToNextRoomResponse\x12?\n" +
	"\x0enew_game_state\x18\x01 \x01(\v2\x19.game.models.v1.GameStateR\fnewGameState2\x9d\x02\n" +
	"\vGameService\x12\x81\x01\n" +
	"\fGetGameState\x12$.game.service.v1.GetGameStateRequest\x1a%.game.service.v1.GetGameStateResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/game/{partnership_id}/state\x12\x89\x01\n" +
	"\x0eMoveToNextRoom\x12&.game.service.v1.MoveToNextRoomRequest\x1a'.game.service.v1.MoveToNextRoomResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/game/{partnership_id}/moveBEZCgithub.com/nineteen-night/empty-room-game/internal/game/pb/game_apib\x06proto3"

var (
	file_game_api_game_proto_rawDescOnce sync.Once
	file_game_api_game_proto_rawDescData []byte
)

func file_game_api_game_proto_rawDescGZIP() []byte {
	file_game_api_game_proto_rawDescOnce.Do(func() {
		file_game_api_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_api_game_proto_rawDesc), len(file_game_api_game_proto_rawDesc)))
	})
	return file_game_api_game_proto_rawDescData
}

var file_game_api_game_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_game_api_game_proto_goTypes = []any{
	(*GetGameStateRequest)(nil),    // 0: game.service.v1.GetGameStateRequest
	(*GetGameStateResponse)(nil),   // 1: game.service.v1.GetGameStateResponse
	(*MoveToNextRoomRequest)(nil),  // 2: game.service.v1.MoveToNextRoomRequest
	(*MoveToNextRoomResponse)(nil), // 3: game.service.v1.MoveToNextRoomResponse
	(*models.GameState)(nil),       // 4: game.models.v1.GameState
}
var file_game_api_game_proto_depIdxs = []int32{
	4, // 0: game.service.v1.GetGameStateResponse.game_state:type_name -> game.models.v1.GameState
	4, // 1: game.service.v1.MoveToNextRoomResponse.new_game_state:type_name -> game.models.v1.GameState
	0, // 2: game.service.v1.GameService.GetGameState:input_type -> game.service.v1.GetGameStateRequest
	2, // 3: game.service.v1.GameService.MoveToNextRoom:input_type -> game.service.v1.MoveToNextRoomRequest
	1, // 4: game.service.v1.GameService.GetGameState:output_type -> game.service.v1.GetGameStateResponse
	3, // 5: game.service.v1.GameService.MoveToNextRoom:output_type -> game.service.v1.MoveToNextRoomResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_game_api_game_proto_init() }
func file_game_api_game_proto_init() {
	if File_game_api_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_api_game_proto_rawDesc), len(file_game_api_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_api_game_proto_goTypes,
		DependencyIndexes: file_game_api_game_proto_depIdxs,
		MessageInfos:      file_game_api_game_proto_msgTypes,
	}.Build()
	File_game_api_game_proto = out.File
	file_game_api_game_proto_goTypes = nil
	file_game_api_game_proto_depIdxs = nil
}
