// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: auth_api/auth.proto

package auth_api

import (
	models "github.com/nineteen-night/empty-room-game/internal/auth/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Регистрация
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_api_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *models.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_auth_api_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUser() *models.User {
	if x != nil {
		return x.User
	}
	return nil
}

// Вход
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_api_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *models.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_api_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetUser() *models.User {
	if x != nil {
		return x.User
	}
	return nil
}

// Партнёрства
type CreatePartnershipRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PartnerUsername string                 `protobuf:"bytes,2,opt,name=partner_username,json=partnerUsername,proto3" json:"partner_username,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreatePartnershipRequest) Reset() {
	*x = CreatePartnershipRequest{}
	mi := &file_auth_api_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartnershipRequest) ProtoMessage() {}

func (x *CreatePartnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartnershipRequest.ProtoReflect.Descriptor instead.
func (*CreatePartnershipRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePartnershipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePartnershipRequest) GetPartnerUsername() string {
	if x != nil {
		return x.PartnerUsername
	}
	return ""
}

type CreatePartnershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partnership   *models.Partnership    `protobuf:"bytes,1,opt,name=partnership,proto3" json:"partnership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePartnershipResponse) Reset() {
	*x = CreatePartnershipResponse{}
	mi := &file_auth_api_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartnershipResponse) ProtoMessage() {}

func (x *CreatePartnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartnershipResponse.ProtoReflect.Descriptor instead.
func (*CreatePartnershipResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePartnershipResponse) GetPartnership() *models.Partnership {
	if x != nil {
		return x.Partnership
	}
	return nil
}

type TerminatePartnershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartnershipId string                 `protobuf:"bytes,1,opt,name=partnership_id,json=partnershipId,proto3" json:"partnership_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminatePartnershipRequest) Reset() {
	*x = TerminatePartnershipRequest{}
	mi := &file_auth_api_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminatePartnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminatePartnershipRequest) ProtoMessage() {}

func (x *TerminatePartnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminatePartnershipRequest.ProtoReflect.Descriptor instead.
func (*TerminatePartnershipRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{6}
}

func (x *TerminatePartnershipRequest) GetPartnershipId() string {
	if x != nil {
		return x.PartnershipId
	}
	return ""
}

type TerminatePartnershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminatePartnershipResponse) Reset() {
	*x = TerminatePartnershipResponse{}
	mi := &file_auth_api_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminatePartnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminatePartnershipResponse) ProtoMessage() {}

func (x *TerminatePartnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminatePartnershipResponse.ProtoReflect.Descriptor instead.
func (*TerminatePartnershipResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{7}
}

func (x *TerminatePartnershipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Пользователь
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_auth_api_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *models.User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_auth_api_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserResponse) GetUser() *models.User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_auth_api_auth_proto protoreflect.FileDescriptor

const file_auth_api_auth_proto_rawDesc = "" +
	"\n" +
	"\x13auth_api/auth.proto\x12\x0fauth.service.v1\x1a\x17models/auth_model.proto\x1a\x1cgoogle/api/annotations.proto\"_\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"<\n" +
	"\x10RegisterResponse\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.auth.models.v1.UserR\x04user\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"9\n" +
	"\rLoginResponse\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.auth.models.v1.UserR\x04user\"^\n" +
	"\x18CreatePartnershipRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10partner_username\x18\x02 \x01(\tR\x0fpartnerUsername\"Z\n" +
	"\x19CreatePartnershipResponse\x12=\n" +
	"\vpartnership\x18\x01 \x01(\v2\x1b.auth.models.v1.PartnershipR\vpartnership\"D\n" +
	"\x1bTerminatePartnershipRequest\x12%\n" +
	"\x0epartnership_id\x18\x01 \x01(\tR\rpartnershipId\"8\n" +
	"\x1cTerminatePartnershipResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x0fGetUserResponse\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.auth.models.v1.UserR\x04user2\xe3\x04\n" +
	"\vAuthService\x12j\n" +
	"\bRegister\x12 .auth.service.v1.RegisterRequest\x1a!.auth.service.v1.RegisterResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/auth/register\x12^\n" +
	"\x05Login\x12\x1d.auth.service.v1.LoginRequest\x1a\x1e.auth.service.v1.LoginResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/auth/login\x12\x83\x01\n" +
	"\x11CreatePartnership\x12).auth.service.v1.CreatePartnershipRequest\x1a*.auth.service.v1.CreatePartnershipResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/partnership\x12\x9a\x01\n" +
	"\x14TerminatePartnership\x12,.auth.service.v1.TerminatePartnershipRequest\x1a-.auth.service.v1.TerminatePartnershipResponse\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/partnership/{partnership_id}\x12e\n" +
	"\aGetUser\x12\x1f.auth.service.v1.GetUserRequest\x1a .auth.service.v1.GetUserResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/user/{user_id}BEZCgithub.com/nineteen-night/empty-room-game/internal/auth/pb/auth_apib\x06proto3"

var (
	file_auth_api_auth_proto_rawDescOnce sync.Once
	file_auth_api_auth_proto_rawDescData []byte
)

func file_auth_api_auth_proto_rawDescGZIP() []byte {
	file_auth_api_auth_proto_rawDescOnce.Do(func() {
		file_auth_api_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_api_auth_proto_rawDesc), len(file_auth_api_auth_proto_rawDesc)))
	})
	return file_auth_api_auth_proto_rawDescData
}

var file_auth_api_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_auth_api_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),              // 0: auth.service.v1.RegisterRequest
	(*RegisterResponse)(nil),             // 1: auth.service.v1.RegisterResponse
	(*LoginRequest)(nil),                 // 2: auth.service.v1.LoginRequest
	(*LoginResponse)(nil),                // 3: auth.service.v1.LoginResponse
	(*CreatePartnershipRequest)(nil),     // 4: auth.service.v1.CreatePartnershipRequest
	(*CreatePartnershipResponse)(nil),    // 5: auth.service.v1.CreatePartnershipResponse
	(*TerminatePartnershipRequest)(nil),  // 6: auth.service.v1.TerminatePartnershipRequest
	(*TerminatePartnershipResponse)(nil), // 7: auth.service.v1.TerminatePartnershipResponse
	(*GetUserRequest)(nil),               // 8: auth.service.v1.GetUserRequest
	(*GetUserResponse)(nil),              // 9: auth.service.v1.GetUserResponse
	(*models.User)(nil),                  // 10: auth.models.v1.User
	(*models.Partnership)(nil),           // 11: auth.models.v1.Partnership
}
var file_auth_api_auth_proto_depIdxs = []int32{
	10, // 0: auth.service.v1.RegisterResponse.user:type_name -> auth.models.v1.User
	10, // 1: auth.service.v1.LoginResponse.user:type_name -> auth.models.v1.User
	11, // 2: auth.service.v1.CreatePartnershipResponse.partnership:type_name -> auth.models.v1.Partnership
	10, // 3: auth.service.v1.GetUserResponse.user:type_name -> auth.models.v1.User
	0,  // 4: auth.service.v1.AuthService.Register:input_type -> auth.service.v1.RegisterRequest
	2,  // 5: auth.service.v1.AuthService.Login:input_type -> auth.service.v1.LoginRequest
	4,  // 6: auth.service.v1.AuthService.CreatePartnership:input_type -> auth.service.v1.CreatePartnershipRequest
	6,  // 7: auth.service.v1.AuthService.TerminatePartnership:input_type -> auth.service.v1.TerminatePartnershipRequest
	8,  // 8: auth.service.v1.AuthService.GetUser:input_type -> auth.service.v1.GetUserRequest
	1,  // 9: auth.service.v1.AuthService.Register:output_type -> auth.service.v1.RegisterResponse
	3,  // 10: auth.service.v1.AuthService.Login:output_type -> auth.service.v1.LoginResponse
	5,  // 11: auth.service.v1.AuthService.CreatePartnership:output_type -> auth.service.v1.CreatePartnershipResponse
	7,  // 12: auth.service.v1.AuthService.TerminatePartnership:output_type -> auth.service.v1.TerminatePartnershipResponse
	9,  // 13: auth.service.v1.AuthService.GetUser:output_type -> auth.service.v1.GetUserResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_auth_api_auth_proto_init() }
func file_auth_api_auth_proto_init() {
	if File_auth_api_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_api_auth_proto_rawDesc), len(file_auth_api_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_api_auth_proto_goTypes,
		DependencyIndexes: file_auth_api_auth_proto_depIdxs,
		MessageInfos:      file_auth_api_auth_proto_msgTypes,
	}.Build()
	File_auth_api_auth_proto = out.File
	file_auth_api_auth_proto_goTypes = nil
	file_auth_api_auth_proto_depIdxs = nil
}
