// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: auth_api/auth.proto

package auth_api

import (
	models "github.com/nineteen-night/empty-room-game/internal/auth/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запросы для пользователей
type GetUsersByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIDsRequest) Reset() {
	*x = GetUsersByIDsRequest{}
	mi := &file_auth_api_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIDsRequest) ProtoMessage() {}

func (x *GetUsersByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetUsersByIDsRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsersByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetUsersByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*models.UserModel    `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByIDsResponse) Reset() {
	*x = GetUsersByIDsResponse{}
	mi := &file_auth_api_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByIDsResponse) ProtoMessage() {}

func (x *GetUsersByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetUsersByIDsResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsersByIDsResponse) GetUsers() []*models.UserModel {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpsertUsersRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Users         []*models.UserUpsertModel `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUsersRequest) Reset() {
	*x = UpsertUsersRequest{}
	mi := &file_auth_api_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUsersRequest) ProtoMessage() {}

func (x *UpsertUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUsersRequest.ProtoReflect.Descriptor instead.
func (*UpsertUsersRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertUsersRequest) GetUsers() []*models.UserUpsertModel {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpsertUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertUsersResponse) Reset() {
	*x = UpsertUsersResponse{}
	mi := &file_auth_api_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUsersResponse) ProtoMessage() {}

func (x *UpsertUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUsersResponse.ProtoReflect.Descriptor instead.
func (*UpsertUsersResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{3}
}

// Запросы для партнёрств
type GetPartnershipsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartnershipsByIDsRequest) Reset() {
	*x = GetPartnershipsByIDsRequest{}
	mi := &file_auth_api_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartnershipsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartnershipsByIDsRequest) ProtoMessage() {}

func (x *GetPartnershipsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartnershipsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetPartnershipsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GetPartnershipsByIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetPartnershipsByIDsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Partnerships  []*models.PartnershipModel `protobuf:"bytes,1,rep,name=partnerships,proto3" json:"partnerships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartnershipsByIDsResponse) Reset() {
	*x = GetPartnershipsByIDsResponse{}
	mi := &file_auth_api_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartnershipsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartnershipsByIDsResponse) ProtoMessage() {}

func (x *GetPartnershipsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartnershipsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetPartnershipsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GetPartnershipsByIDsResponse) GetPartnerships() []*models.PartnershipModel {
	if x != nil {
		return x.Partnerships
	}
	return nil
}

type UpsertPartnershipsRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Partnerships  []*models.PartnershipUpsertModel `protobuf:"bytes,1,rep,name=partnerships,proto3" json:"partnerships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPartnershipsRequest) Reset() {
	*x = UpsertPartnershipsRequest{}
	mi := &file_auth_api_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPartnershipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPartnershipsRequest) ProtoMessage() {}

func (x *UpsertPartnershipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPartnershipsRequest.ProtoReflect.Descriptor instead.
func (*UpsertPartnershipsRequest) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{6}
}

func (x *UpsertPartnershipsRequest) GetPartnerships() []*models.PartnershipUpsertModel {
	if x != nil {
		return x.Partnerships
	}
	return nil
}

type UpsertPartnershipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertPartnershipsResponse) Reset() {
	*x = UpsertPartnershipsResponse{}
	mi := &file_auth_api_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertPartnershipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertPartnershipsResponse) ProtoMessage() {}

func (x *UpsertPartnershipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_api_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertPartnershipsResponse.ProtoReflect.Descriptor instead.
func (*UpsertPartnershipsResponse) Descriptor() ([]byte, []int) {
	return file_auth_api_auth_proto_rawDescGZIP(), []int{7}
}

var File_auth_api_auth_proto protoreflect.FileDescriptor

const file_auth_api_auth_proto_rawDesc = "" +
	"\n" +
	"\x13auth_api/auth.proto\x12\x0fauth.service.v1\x1a\x17models/auth_model.proto\x1a\x1cgoogle/api/annotations.proto\"(\n" +
	"\x14GetUsersByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"H\n" +
	"\x15GetUsersByIDsResponse\x12/\n" +
	"\x05users\x18\x01 \x03(\v2\x19.auth.models.v1.UserModelR\x05users\"K\n" +
	"\x12UpsertUsersRequest\x125\n" +
	"\x05users\x18\x01 \x03(\v2\x1f.auth.models.v1.UserUpsertModelR\x05users\"\x15\n" +
	"\x13UpsertUsersResponse\"/\n" +
	"\x1bGetPartnershipsByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"d\n" +
	"\x1cGetPartnershipsByIDsResponse\x12D\n" +
	"\fpartnerships\x18\x01 \x03(\v2 .auth.models.v1.PartnershipModelR\fpartnerships\"g\n" +
	"\x19UpsertPartnershipsRequest\x12J\n" +
	"\fpartnerships\x18\x01 \x03(\v2&.auth.models.v1.PartnershipUpsertModelR\fpartnerships\"\x1c\n" +
	"\x1aUpsertPartnershipsResponse2\xab\x04\n" +
	"\vAuthService\x12|\n" +
	"\rGetUsersByIDs\x12%.auth.service.v1.GetUsersByIDsRequest\x1a&.auth.service.v1.GetUsersByIDsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/users/get-by-ids\x12r\n" +
	"\vUpsertUsers\x12#.auth.service.v1.UpsertUsersRequest\x1a$.auth.service.v1.UpsertUsersResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/users/upsert\x12\x98\x01\n" +
	"\x14GetPartnershipsByIDs\x12,.auth.service.v1.GetPartnershipsByIDsRequest\x1a-.auth.service.v1.GetPartnershipsByIDsResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/partnerships/get-by-ids\x12\x8e\x01\n" +
	"\x12UpsertPartnerships\x12*.auth.service.v1.UpsertPartnershipsRequest\x1a+.auth.service.v1.UpsertPartnershipsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/partnerships/upsertBEZCgithub.com/nineteen-night/empty-room-game/internal/auth/pb/auth_apib\x06proto3"

var (
	file_auth_api_auth_proto_rawDescOnce sync.Once
	file_auth_api_auth_proto_rawDescData []byte
)

func file_auth_api_auth_proto_rawDescGZIP() []byte {
	file_auth_api_auth_proto_rawDescOnce.Do(func() {
		file_auth_api_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_api_auth_proto_rawDesc), len(file_auth_api_auth_proto_rawDesc)))
	})
	return file_auth_api_auth_proto_rawDescData
}

var file_auth_api_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_api_auth_proto_goTypes = []any{
	(*GetUsersByIDsRequest)(nil),          // 0: auth.service.v1.GetUsersByIDsRequest
	(*GetUsersByIDsResponse)(nil),         // 1: auth.service.v1.GetUsersByIDsResponse
	(*UpsertUsersRequest)(nil),            // 2: auth.service.v1.UpsertUsersRequest
	(*UpsertUsersResponse)(nil),           // 3: auth.service.v1.UpsertUsersResponse
	(*GetPartnershipsByIDsRequest)(nil),   // 4: auth.service.v1.GetPartnershipsByIDsRequest
	(*GetPartnershipsByIDsResponse)(nil),  // 5: auth.service.v1.GetPartnershipsByIDsResponse
	(*UpsertPartnershipsRequest)(nil),     // 6: auth.service.v1.UpsertPartnershipsRequest
	(*UpsertPartnershipsResponse)(nil),    // 7: auth.service.v1.UpsertPartnershipsResponse
	(*models.UserModel)(nil),              // 8: auth.models.v1.UserModel
	(*models.UserUpsertModel)(nil),        // 9: auth.models.v1.UserUpsertModel
	(*models.PartnershipModel)(nil),       // 10: auth.models.v1.PartnershipModel
	(*models.PartnershipUpsertModel)(nil), // 11: auth.models.v1.PartnershipUpsertModel
}
var file_auth_api_auth_proto_depIdxs = []int32{
	8,  // 0: auth.service.v1.GetUsersByIDsResponse.users:type_name -> auth.models.v1.UserModel
	9,  // 1: auth.service.v1.UpsertUsersRequest.users:type_name -> auth.models.v1.UserUpsertModel
	10, // 2: auth.service.v1.GetPartnershipsByIDsResponse.partnerships:type_name -> auth.models.v1.PartnershipModel
	11, // 3: auth.service.v1.UpsertPartnershipsRequest.partnerships:type_name -> auth.models.v1.PartnershipUpsertModel
	0,  // 4: auth.service.v1.AuthService.GetUsersByIDs:input_type -> auth.service.v1.GetUsersByIDsRequest
	2,  // 5: auth.service.v1.AuthService.UpsertUsers:input_type -> auth.service.v1.UpsertUsersRequest
	4,  // 6: auth.service.v1.AuthService.GetPartnershipsByIDs:input_type -> auth.service.v1.GetPartnershipsByIDsRequest
	6,  // 7: auth.service.v1.AuthService.UpsertPartnerships:input_type -> auth.service.v1.UpsertPartnershipsRequest
	1,  // 8: auth.service.v1.AuthService.GetUsersByIDs:output_type -> auth.service.v1.GetUsersByIDsResponse
	3,  // 9: auth.service.v1.AuthService.UpsertUsers:output_type -> auth.service.v1.UpsertUsersResponse
	5,  // 10: auth.service.v1.AuthService.GetPartnershipsByIDs:output_type -> auth.service.v1.GetPartnershipsByIDsResponse
	7,  // 11: auth.service.v1.AuthService.UpsertPartnerships:output_type -> auth.service.v1.UpsertPartnershipsResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_auth_api_auth_proto_init() }
func file_auth_api_auth_proto_init() {
	if File_auth_api_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_api_auth_proto_rawDesc), len(file_auth_api_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_api_auth_proto_goTypes,
		DependencyIndexes: file_auth_api_auth_proto_depIdxs,
		MessageInfos:      file_auth_api_auth_proto_msgTypes,
	}.Build()
	File_auth_api_auth_proto = out.File
	file_auth_api_auth_proto_goTypes = nil
	file_auth_api_auth_proto_depIdxs = nil
}
