// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: auth_api/auth.proto

package auth_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_GetUsersByIDs_FullMethodName        = "/auth.service.v1.AuthService/GetUsersByIDs"
	AuthService_UpsertUsers_FullMethodName          = "/auth.service.v1.AuthService/UpsertUsers"
	AuthService_GetPartnershipsByIDs_FullMethodName = "/auth.service.v1.AuthService/GetPartnershipsByIDs"
	AuthService_UpsertPartnerships_FullMethodName   = "/auth.service.v1.AuthService/UpsertPartnerships"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	// Пользователи
	GetUsersByIDs(ctx context.Context, in *GetUsersByIDsRequest, opts ...grpc.CallOption) (*GetUsersByIDsResponse, error)
	UpsertUsers(ctx context.Context, in *UpsertUsersRequest, opts ...grpc.CallOption) (*UpsertUsersResponse, error)
	// Партнёрства
	GetPartnershipsByIDs(ctx context.Context, in *GetPartnershipsByIDsRequest, opts ...grpc.CallOption) (*GetPartnershipsByIDsResponse, error)
	UpsertPartnerships(ctx context.Context, in *UpsertPartnershipsRequest, opts ...grpc.CallOption) (*UpsertPartnershipsResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) GetUsersByIDs(ctx context.Context, in *GetUsersByIDsRequest, opts ...grpc.CallOption) (*GetUsersByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersByIDsResponse)
	err := c.cc.Invoke(ctx, AuthService_GetUsersByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpsertUsers(ctx context.Context, in *UpsertUsersRequest, opts ...grpc.CallOption) (*UpsertUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertUsersResponse)
	err := c.cc.Invoke(ctx, AuthService_UpsertUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetPartnershipsByIDs(ctx context.Context, in *GetPartnershipsByIDsRequest, opts ...grpc.CallOption) (*GetPartnershipsByIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPartnershipsByIDsResponse)
	err := c.cc.Invoke(ctx, AuthService_GetPartnershipsByIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpsertPartnerships(ctx context.Context, in *UpsertPartnershipsRequest, opts ...grpc.CallOption) (*UpsertPartnershipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertPartnershipsResponse)
	err := c.cc.Invoke(ctx, AuthService_UpsertPartnerships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	// Пользователи
	GetUsersByIDs(context.Context, *GetUsersByIDsRequest) (*GetUsersByIDsResponse, error)
	UpsertUsers(context.Context, *UpsertUsersRequest) (*UpsertUsersResponse, error)
	// Партнёрства
	GetPartnershipsByIDs(context.Context, *GetPartnershipsByIDsRequest) (*GetPartnershipsByIDsResponse, error)
	UpsertPartnerships(context.Context, *UpsertPartnershipsRequest) (*UpsertPartnershipsResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) GetUsersByIDs(context.Context, *GetUsersByIDsRequest) (*GetUsersByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsersByIDs not implemented")
}
func (UnimplementedAuthServiceServer) UpsertUsers(context.Context, *UpsertUsersRequest) (*UpsertUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertUsers not implemented")
}
func (UnimplementedAuthServiceServer) GetPartnershipsByIDs(context.Context, *GetPartnershipsByIDsRequest) (*GetPartnershipsByIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPartnershipsByIDs not implemented")
}
func (UnimplementedAuthServiceServer) UpsertPartnerships(context.Context, *UpsertPartnershipsRequest) (*UpsertPartnershipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertPartnerships not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_GetUsersByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUsersByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUsersByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUsersByIDs(ctx, req.(*GetUsersByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpsertUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpsertUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpsertUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpsertUsers(ctx, req.(*UpsertUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetPartnershipsByIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPartnershipsByIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetPartnershipsByIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetPartnershipsByIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetPartnershipsByIDs(ctx, req.(*GetPartnershipsByIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpsertPartnerships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPartnershipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpsertPartnerships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpsertPartnerships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpsertPartnerships(ctx, req.(*UpsertPartnershipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.service.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsersByIDs",
			Handler:    _AuthService_GetUsersByIDs_Handler,
		},
		{
			MethodName: "UpsertUsers",
			Handler:    _AuthService_UpsertUsers_Handler,
		},
		{
			MethodName: "GetPartnershipsByIDs",
			Handler:    _AuthService_GetPartnershipsByIDs_Handler,
		},
		{
			MethodName: "UpsertPartnerships",
			Handler:    _AuthService_UpsertPartnerships_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_api/auth.proto",
}
